export function makeRelease(overrides = {}) {
  const entity = {
    ancient_name_grc: 'Αἴγινα',
    ancient_region_authority_id: 'region-saronikos',
    chronologies: [
      {
        chronology_basis: 'occupation_window',
        chronology_id: 'chronology-city-aegina-city-primary',
        display_cutoff: true,
        end_precision: 'display_cutoff',
        end_year: 600,
        entity_id: 'city-aegina-city',
        label_el: '1000 π.Χ.–600 μ.Χ. (όριο άτλαντα)',
        label_en: '1000 BCE–600 CE (atlas display cutoff)',
        note_el: 'Το 600 μ.Χ. είναι όριο του άτλαντα.',
        note_en: '600 CE is the atlas display cutoff.',
        review_state: 'reviewed',
        source_id: 'src-pleiades-579853',
        start_precision: 'approximate',
        start_year: -1000,
        temporal_precision: 'approximate',
      },
    ],
    collections: 'city|colony',
    data_version: '1.0.0',
    description_el: 'Νησιωτική εμπορική και ναυτική δύναμη.',
    description_en: 'An island trading and naval power.',
    entity_class: 'settlement',
    entity_id: 'city-aegina-city',
    entity_subtype: 'polis',
    external_ids: [
      {
        entity_id: 'city-aegina-city',
        external_id: 'ext-pleiades-city-aegina-city',
        identifier: '579853',
        match_type: 'exact',
        place_id: null,
        scheme: 'pleiades',
        source_id: 'src-pleiades-579853',
        uri: 'https://pleiades.stoa.org/places/579853',
      },
    ],
    last_reviewed: '2026-08-14',
    legacy_id: 'city-aegina-city',
    legacy_subtype: 'polis',
    location_certainty: 'high',
    media: [
      {
        alt_el: 'Αίγινα: αρχαιολογική άποψη',
        alt_en: 'Aegina: archaeological view',
        attribution: 'Example Photographer / Wikimedia Commons / CC BY-SA 4.0',
        caption_el: 'Αίγινα · Αρχαιολογική άποψη',
        caption_en: 'Aegina · Archaeological view',
        creator: 'Example Photographer',
        entity_id: 'city-aegina-city',
        file_path: 'assets/media/city-aegina-city/01.webp',
        height: 900,
        license: 'CC BY-SA 4.0',
        license_url: 'https://creativecommons.org/licenses/by-sa/4.0/',
        media_id: 'media-city-aegina-city-01',
        original_url: 'https://upload.wikimedia.org/example-01.jpg',
        position: 1,
        retrieved_on: '2026-08-15',
        review_state: 'reviewed',
        role: 'primary',
        sha256: 'a'.repeat(64),
        source_url: 'https://commons.wikimedia.org/wiki/File:Example_01.jpg',
        title: 'Example 01.jpg',
        width: 1440,
      },
      {
        alt_el: 'Αίγινα: αρχαίο μνημείο',
        alt_en: 'Aegina: ancient monument',
        attribution: 'Example Photographer / Wikimedia Commons / CC BY 4.0',
        caption_el: 'Αίγινα · Αρχαίο μνημείο',
        caption_en: 'Aegina · Ancient monument',
        creator: 'Example Photographer',
        entity_id: 'city-aegina-city',
        file_path: 'assets/media/city-aegina-city/02.webp',
        height: 900,
        license: 'CC BY 4.0',
        license_url: 'https://creativecommons.org/licenses/by/4.0/',
        media_id: 'media-city-aegina-city-02',
        original_url: 'https://upload.wikimedia.org/example-02.jpg',
        position: 2,
        retrieved_on: '2026-08-15',
        review_state: 'reviewed',
        role: 'gallery',
        sha256: 'b'.repeat(64),
        source_url: 'https://commons.wikimedia.org/wiki/File:Example_02.jpg',
        title: 'Example 02.jpg',
        width: 1440,
      },
    ],
    names: [
      {
        end_year: null,
        entity_id: 'city-aegina-city',
        is_preferred: true,
        language: 'el',
        name: 'Αίγινα',
        name_id: 'name-city-aegina-city-el-preferred',
        name_type: 'preferred',
        review_state: 'reviewed',
        script: 'Grek',
        source_id: 'src-pleiades-579853',
        start_year: null,
      },
      {
        end_year: null,
        entity_id: 'city-aegina-city',
        is_preferred: true,
        language: 'en',
        name: 'Aegina',
        name_id: 'name-city-aegina-city-en-preferred',
        name_type: 'preferred',
        review_state: 'reviewed',
        script: 'Latn',
        source_id: 'src-pleiades-579853',
        start_year: null,
      },
      {
        end_year: null,
        entity_id: 'city-aegina-city',
        is_preferred: false,
        language: 'grc',
        name: 'Αἴγινα',
        name_id: 'name-city-aegina-city-grc-ancient',
        name_type: 'ancient',
        review_state: 'reviewed',
        script: 'Grek',
        source_id: 'src-pleiades-579853',
        start_year: null,
      },
      {
        end_year: null,
        entity_id: 'city-aegina-city',
        is_preferred: false,
        language: 'en',
        name: 'Aigina',
        name_id: 'name-city-aegina-city-en-transliterated',
        name_type: 'transliterated',
        review_state: 'reviewed',
        script: 'Latn',
        source_id: 'src-pleiades-579853',
        start_year: null,
      },
    ],
    places: [
      {
        coordinate_source_text: 'Pleiades representative point',
        country_iso2: 'GR',
        country_iso3: 'GRC',
        entity_id: 'city-aegina-city',
        geometry_geojson: { coordinates: [23.423668, 37.750149], type: 'Point' },
        geometry_role: 'site',
        geometry_wkt: 'POINT (23.423668 37.750149)',
        latitude: 37.750149,
        location_certainty: 'high',
        location_precision: 'exact',
        longitude: 23.423668,
        modern_country_el: 'Ελλάδα',
        modern_country_en: 'Greece',
        modern_locality: 'Αίγινα',
        place_id: 'place-city-aegina-city',
        review_state: 'reviewed',
        source_id: 'src-pleiades-579853',
        spatial_note_el: null,
        spatial_note_en: null,
      },
    ],
    preferred_name_el: 'Αίγινα',
    preferred_name_en: 'Aegina',
    record_confidence: 'high',
    relationships: [
      {
        certainty: 'high',
        migration_evidence_el: null,
        object_authority_id: null,
        object_entity_id: 'city-athens-attica',
        object_label_el: 'Αθήνα',
        object_label_en: 'Athens',
        predicate: 'associated_with_settlement',
        relationship_id: 'rel-aegina-athens',
        review_state: 'reviewed',
        source_id: 'src-pleiades-579853',
        subject_entity_id: 'city-aegina-city',
      },
    ],
    review_state: 'reviewed',
    reviewer: 'Test fixture editor',
    sanctuary_function_tags: null,
    sanctuary_scope: null,
    sanctuary_setting: null,
    source_origin: 'fixture.csv',
    source_support: [
      {
        citation: 'Aigina. Pleiades.',
        is_primary: true,
        publisher: 'Pleiades',
        source_id: 'src-pleiades-579853',
        support_scope: 'identity',
        title: 'Aigina',
        url: 'https://pleiades.stoa.org/places/579853',
      },
      {
        citation: 'Aigina. Pleiades.',
        is_primary: true,
        publisher: 'Pleiades',
        source_id: 'src-pleiades-579853',
        support_scope: 'geometry',
        title: 'Aigina',
        url: 'https://pleiades.stoa.org/places/579853',
      },
    ],
    temporal_precision: 'approximate',
    translation_status: 'machine_assisted_reviewed',
  };

  return {
    authorities: [
      {
        authority_id: 'region-saronikos',
        authority_type: 'ancient_region',
        preferred_label_el: 'Σαρωνικός',
        preferred_label_en: 'Saronic Gulf',
        review_state: 'reviewed',
        source_id: 'src-atlas',
        uri: null,
      },
    ],
    dataset: {
      entity_count: 1,
      generated_on: '2026-08-15',
      license_note: 'Fixture only.',
      title_el: 'Άτλας δοκιμής',
      title_en: 'Test atlas',
      version: '1.0.0',
    },
    entities: [entity],
    sources: [
      {
        accessed_on: '2026-08-15',
        citation: 'Aigina. Pleiades.',
        language: 'en',
        license: 'CC BY 3.0',
        notes: null,
        publisher: 'Pleiades',
        source_class: 'scholarly_gazetteer',
        source_id: 'src-pleiades-579853',
        title: 'Aigina',
        url: 'https://pleiades.stoa.org/places/579853',
        url_status: 'ok',
      },
    ],
    ...overrides,
  };
}
